name: Create Feature Branch on Issue Creation

permissions:
  contents: write
  issues: write

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Create feature branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          ISSUE_TITLE_CLEAN="${ISSUE_TITLE// /-}"
          ISSUE_TITLE_CLEAN="${ISSUE_TITLE_CLEAN//[^a-zA-Z0-9가-힣_-]/}"
          BRANCH_NAME="feature/#${ISSUE_NUMBER}_${ISSUE_TITLE_CLEAN}"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
